/*
# Ingresos, múltiples tarjetas y origen de gasto

## Resumen
Esta migración agrega soporte para:
1. Registrar dos ingresos independientes ("Sueldo Papá" y "Sueldo Mamá").
2. Múltiples tarjetas de crédito (ej: Santander, Naranja), cada una con su propio día de cierre.
3. Asociar cada gasto a un origen ("Sueldo Papá" o "Sueldo Mamá").
4. Asociar cada compra en cuotas a una tarjeta específica.
5. Nuevas categorías de gasto: "Departamento" y "Ferretería".

## Tablas nuevas

### `incomes`
- `id` (int8, primary key, identity) — identificador único.
- `label` (text, not null) — nombre del ingreso, ej: "Sueldo Papá".
- `amount` (float8, not null, default 0) — monto del ingreso.
- `created_at` (timestamptz, default now()).
- `updated_at` (timestamptz, default now()).
- Se insertan dos filas por defecto: "Sueldo Papá" y "Sueldo Mamá".

### `cards`
- `id` (int8, primary key, identity) — identificador único.
- `name` (text, not null) — nombre de la tarjeta, ej: "Santander".
- `close_day` (int4, not null, default 15) — día de cierre del resumen.
- `created_at` (timestamptz, default now()).
- Se insertan dos tarjetas por defecto: "Santander" (cierre día 15) y "Naranja" (cierre día 20).

## Tablas modificadas

### `expenses`
- Nueva columna `source` (text, nullable) — origen del dinero: "Sueldo Papá" o "Sueldo Mamá".

### `card_purchases`
- Nueva columna `card_id` (int8, nullable) — referencia a `cards(id)`.
- Foreign key `card_purchases.card_id → cards(id) ON DELETE SET NULL`.

## Seguridad (RLS)
- Se habilita RLS en todas las tablas.
- Todas las políticas usan `TO anon, authenticated` con `USING (true)` / `WITH CHECK (true)` porque es una app single-tenant sin login (datos intencionalmente compartidos).
- 4 políticas por tabla (SELECT, INSERT, UPDATE, DELETE).

## Notas
1. Es una app sin autenticación; el frontend usa la anon key, por lo que todas las políticas deben incluir `anon`.
2. No se eliminan columnas ni tablas existentes; solo se agregan.
3. Las nuevas categorías se agregan solo en el frontend (HTML `<option>`).
*/

-- ═══ Tabla: incomes ═══
CREATE TABLE IF NOT EXISTS incomes (
    id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label      text NOT NULL,
    amount     double precision NOT NULL DEFAULT 0,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

ALTER TABLE incomes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_incomes" ON incomes;
CREATE POLICY "anon_select_incomes" ON incomes FOR SELECT
    TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_incomes" ON incomes;
CREATE POLICY "anon_insert_incomes" ON incomes FOR INSERT
    TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_incomes" ON incomes;
CREATE POLICY "anon_update_incomes" ON incomes FOR UPDATE
    TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_incomes" ON incomes;
CREATE POLICY "anon_delete_incomes" ON incomes FOR DELETE
    TO anon, authenticated USING (true);

-- Insertar ingresos por defecto si no existen
INSERT INTO incomes (label, amount)
SELECT 'Sueldo Papá', 0
WHERE NOT EXISTS (SELECT 1 FROM incomes WHERE label = 'Sueldo Papá');

INSERT INTO incomes (label, amount)
SELECT 'Sueldo Mamá', 0
WHERE NOT EXISTS (SELECT 1 FROM incomes WHERE label = 'Sueldo Mamá');

-- ═══ Tabla: cards ═══
CREATE TABLE IF NOT EXISTS cards (
    id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       text NOT NULL,
    close_day  integer NOT NULL DEFAULT 15,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE cards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_cards" ON cards;
CREATE POLICY "anon_select_cards" ON cards FOR SELECT
    TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_cards" ON cards;
CREATE POLICY "anon_insert_cards" ON cards FOR INSERT
    TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_cards" ON cards;
CREATE POLICY "anon_update_cards" ON cards FOR UPDATE
    TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_cards" ON cards;
CREATE POLICY "anon_delete_cards" ON cards FOR DELETE
    TO anon, authenticated USING (true);

-- Insertar tarjetas por defecto si no existen
INSERT INTO cards (name, close_day)
SELECT 'Santander', 15
WHERE NOT EXISTS (SELECT 1 FROM cards WHERE name = 'Santander');

INSERT INTO cards (name, close_day)
SELECT 'Naranja', 20
WHERE NOT EXISTS (SELECT 1 FROM cards WHERE name = 'Naranja');

-- ═══ Tabla: expenses (nueva columna source) ═══
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'expenses' AND column_name = 'source'
    ) THEN
        ALTER TABLE expenses ADD COLUMN source text;
    END IF;
END $$;

ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_expenses" ON expenses;
CREATE POLICY "anon_select_expenses" ON expenses FOR SELECT
    TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_expenses" ON expenses;
CREATE POLICY "anon_insert_expenses" ON expenses FOR INSERT
    TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_expenses" ON expenses;
CREATE POLICY "anon_update_expenses" ON expenses FOR UPDATE
    TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_expenses" ON expenses;
CREATE POLICY "anon_delete_expenses" ON expenses FOR DELETE
    TO anon, authenticated USING (true);

-- ═══ Tabla: card_purchases (nueva columna card_id) ═══
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'card_purchases' AND column_name = 'card_id'
    ) THEN
        ALTER TABLE card_purchases ADD COLUMN card_id bigint REFERENCES cards(id) ON DELETE SET NULL;
    END IF;
END $$;

ALTER TABLE card_purchases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_card_purchases" ON card_purchases;
CREATE POLICY "anon_select_card_purchases" ON card_purchases FOR SELECT
    TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_card_purchases" ON card_purchases;
CREATE POLICY "anon_insert_card_purchases" ON card_purchases FOR INSERT
    TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_card_purchases" ON card_purchases;
CREATE POLICY "anon_update_card_purchases" ON card_purchases FOR UPDATE
    TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_card_purchases" ON card_purchases;
CREATE POLICY "anon_delete_card_purchases" ON card_purchases FOR DELETE
    TO anon, authenticated USING (true);
