/*
# Crear tablas de finanzas familiares con autenticación y aislamiento por usuario

## Resumen
Esta migración crea todas las tablas necesarias para la app "Gastos Familiares":
- expenses: gastos individuales con categoría, origen, fecha y monto.
- incomes: dos ingresos independientes ("Sueldo Papá" y "Sueldo Mamá").
- cards: múltiples tarjetas de crédito (cierre fijo día 15).
- card_purchases: compras en cuotas asociadas a una tarjeta.

Todas las tablas tienen columna `user_id` que referencia `auth.users(id)` con
`DEFAULT auth.uid()` para que los inserts del frontend funcionen sin pasar
el user_id explícitamente.

## Aislamiento de datos (RLS)
- RLS habilitado en todas las tablas.
- Policias scoped TO authenticated con ownership check `auth.uid() = user_id`.
- Cada usuario (papás, hermana) solo ve y modifica sus propios datos.
- Sin políticas para anon — la app requiere login.

## Tablas nuevas

### `expenses`
- id (bigint, PK, identity)
- user_id (uuid, NOT NULL, DEFAULT auth.uid(), FK → auth.users ON DELETE CASCADE)
- name (text, not null) — descripción del gasto
- amount (double precision, not null) — monto
- category (text, not null) — categoría (Alimentación, Transporte, Compras, Departamento, Ferretería, Otro)
- source (text, nullable) — origen del dinero: "Sueldo Papá" o "Sueldo Mamá"
- date (date, not null) — fecha del gasto
- created_at (timestamptz, default now())

### `incomes`
- id (bigint, PK, identity)
- user_id (uuid, NOT NULL, DEFAULT auth.uid(), FK → auth.users ON DELETE CASCADE)
- label (text, not null) — "Sueldo Papá" o "Sueldo Mamá"
- amount (double precision, not null, default 0)
- created_at (timestamptz, default now())
- updated_at (timestamptz, default now())
- UNIQUE(user_id, label) — un usuario no puede tener dos ingresos con el mismo label

### `cards`
- id (bigint, PK, identity)
- user_id (uuid, NOT NULL, DEFAULT auth.uid(), FK → auth.users ON DELETE CASCADE)
- name (text, not null) — nombre de la tarjeta
- close_day (integer, not null, default 15) — día de cierre (fijo en 15)
- created_at (timestamptz, default now())

### `card_purchases`
- id (bigint, PK, identity)
- user_id (uuid, NOT NULL, DEFAULT auth.uid(), FK → auth.users ON DELETE CASCADE)
- name (text, not null) — producto comprado
- amount (double precision, not null) — monto total
- installments (integer, not null) — cantidad total de cuotas
- paidCount (integer, not null, default 0) — cuotas ya pagadas
- card_id (bigint, nullable, FK → cards(id) ON DELETE SET NULL)
- purchaseDate (date, not null) — mes de compra
- firstInstallmentDate (date, not null) — fecha de vencimiento de la primera cuota
- created_at (timestamptz, default now())

## Seguridad
- RLS habilitado en las 4 tablas.
- 4 políticas por tabla (SELECT, INSERT, UPDATE, DELETE), todas TO authenticated.
- Ownership check: auth.uid() = user_id en USING y WITH CHECK.
- No hay políticas para anon — el acceso requiere sesión autenticada.

## Notas
1. El DEFAULT auth.uid() en user_id permite que el frontend haga insert({ name, amount, ... }) sin pasar user_id.
2. UNIQUE(user_id, label) en incomes evita duplicados por usuario.
3. close_day se mantiene en 15 fijo pero se guarda por si cambia en el futuro.
4. Las categorías se validan en el frontend; la BD acepta cualquier texto.
*/

-- ═══ Tabla: expenses ═══
CREATE TABLE IF NOT EXISTS expenses (
    id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    name       text NOT NULL,
    amount     double precision NOT NULL,
    category   text NOT NULL,
    source     text,
    date       date NOT NULL,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_expenses" ON expenses;
CREATE POLICY "select_own_expenses" ON expenses FOR SELECT
    TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_expenses" ON expenses;
CREATE POLICY "insert_own_expenses" ON expenses FOR INSERT
    TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_expenses" ON expenses;
CREATE POLICY "update_own_expenses" ON expenses FOR UPDATE
    TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_expenses" ON expenses;
CREATE POLICY "delete_own_expenses" ON expenses FOR DELETE
    TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_expenses_user_id ON expenses(user_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(date DESC);

-- ═══ Tabla: incomes ═══
CREATE TABLE IF NOT EXISTS incomes (
    id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    label      text NOT NULL,
    amount     double precision NOT NULL DEFAULT 0,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    UNIQUE(user_id, label)
);

ALTER TABLE incomes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_incomes" ON incomes;
CREATE POLICY "select_own_incomes" ON incomes FOR SELECT
    TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_incomes" ON incomes;
CREATE POLICY "insert_own_incomes" ON incomes FOR INSERT
    TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_incomes" ON incomes;
CREATE POLICY "update_own_incomes" ON incomes FOR UPDATE
    TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_incomes" ON incomes;
CREATE POLICY "delete_own_incomes" ON incomes FOR DELETE
    TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_incomes_user_id ON incomes(user_id);

-- ═══ Tabla: cards ═══
CREATE TABLE IF NOT EXISTS cards (
    id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    name       text NOT NULL,
    close_day  integer NOT NULL DEFAULT 15,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE cards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_cards" ON cards;
CREATE POLICY "select_own_cards" ON cards FOR SELECT
    TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_cards" ON cards;
CREATE POLICY "insert_own_cards" ON cards FOR INSERT
    TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_cards" ON cards;
CREATE POLICY "update_own_cards" ON cards FOR UPDATE
    TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_cards" ON cards;
CREATE POLICY "delete_own_cards" ON cards FOR DELETE
    TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_cards_user_id ON cards(user_id);

-- ═══ Tabla: card_purchases ═══
CREATE TABLE IF NOT EXISTS card_purchases (
    id                   bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id              uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    name                 text NOT NULL,
    amount               double precision NOT NULL,
    installments         integer NOT NULL,
    "paidCount"          integer NOT NULL DEFAULT 0,
    card_id              bigint REFERENCES cards(id) ON DELETE SET NULL,
    "purchaseDate"       date NOT NULL,
    "firstInstallmentDate" date NOT NULL,
    created_at           timestamptz DEFAULT now()
);

ALTER TABLE card_purchases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_card_purchases" ON card_purchases;
CREATE POLICY "select_own_card_purchases" ON card_purchases FOR SELECT
    TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_card_purchases" ON card_purchases;
CREATE POLICY "insert_own_card_purchases" ON card_purchases FOR INSERT
    TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_card_purchases" ON card_purchases;
CREATE POLICY "update_own_card_purchases" ON card_purchases FOR UPDATE
    TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_card_purchases" ON card_purchases;
CREATE POLICY "delete_own_card_purchases" ON card_purchases FOR DELETE
    TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_card_purchases_user_id ON card_purchases(user_id);
CREATE INDEX IF NOT EXISTS idx_card_purchases_card_id ON card_purchases(card_id);